-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.apps
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    icon text COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    developer character varying(255) COLLATE pg_catalog."default",
    version character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT apps_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logs
(
    id serial NOT NULL,
    user_id integer,
    action character varying(50) COLLATE pg_catalog."default",
    app_id integer,
    "timestamp" timestamp without time zone NOT NULL,
    details jsonb,
    CONSTRAINT logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.open_windows
(
    id serial NOT NULL,
    user_id integer,
    app_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    position_x integer,
    position_y integer,
    size_width integer,
    size_height integer,
    is_maximized boolean DEFAULT false,
    is_minimized boolean DEFAULT false,
    z_index integer,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT open_windows_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_installed_apps
(
    id serial NOT NULL,
    user_id integer,
    app_id integer,
    CONSTRAINT user_installed_apps_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    theme character varying(50) COLLATE pg_catalog."default" DEFAULT 'light'::character varying,
    language character varying(10) COLLATE pg_catalog."default" DEFAULT 'en'::character varying,
    created_at timestamp without time zone NOT NULL,
    last_login timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT logs_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.apps (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.open_windows
    ADD CONSTRAINT open_windows_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.apps (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.open_windows
    ADD CONSTRAINT open_windows_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_installed_apps
    ADD CONSTRAINT user_installed_apps_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.apps (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_installed_apps
    ADD CONSTRAINT user_installed_apps_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


-- Deux ajouts : 
ALTER TABLE public.users ADD "path" text NULL;
ALTER TABLE public.apps ADD "type" varchar NULL;


END;
